### ISSUE TITLE
Is a font missing on my system?

### ISSUE THREAD

**Issue by johnblommers** [staff-rs/staff#16]
When I convert the cited `example.ly` file there are two notes with rectangles beside them suggesting that `staff` is expecting a font missing on my system. No messages arert to this. This is the SVG file:

![Notes](https://user-images.githubusercontent.com/8484427/208213170-7be78e1d-7831-49af-8593-5c8fd042072e.svg)

**Comment by matthunz** [comment]
Ah yeah right now the crate uses Noto Music by default but there should definitely be an option to change it

For now I'll definitely add that to the readme
